### ISSUE TITLE
any plans to support export to .json?

### ISSUE THREAD

**Issue by mreinstein** [andrewrk/node-tmx-parser#11]
it would be really nice to be able to work directly with .tmx files and be able to export them to json programmatically rather than having to do it from the tile gui.

**Comment by andrewrk** [comment]
why not just call `JSON.stringify()` on the result that this module gives you?

**Comment by mreinstein** [comment]
I tried that. It gives an error about not being able to stringify an object with cyclic dependencies.

**Comment by andrewrk** [comment]
I think I'm going to say "no" to this feature request. Export json from tiled or remove the cyclic dependencies from tmx parser output.
