### ISSUE TITLE
How can I know if an object was rotated?

### ISSUE THREAD

**Issue by Romuloalmeida** [andrewrk/node-tmx-parser#22]
Hi guys,

I'm encountering difficulties to know if one object was rotated for example 180 degrees or 90 and so on.

Can you help me, please?

Thank you in advanced!

**Comment by iErcann** [comment]
Check the current index of your tile in the flip arrays.
` layer.tiles[index] ` is your current tile

So you can just check if your tile is flipped like this: 
` if (layer.verticalFlips[index]) { .. } `  
` if (layer.horizontalFlips[index]) { .. } `  
` if (layer.diagonalFlips[index]) { .. } `  

There is a PIXI implementation here: https://github.com/Reynau/tiled-to-pixi/blob/master/src/Tile.js#L32

**Comment by Romuloalmeida** [comment]
Thank you so much!
