### ISSUE TITLE
Support png/base64 encoding optionally

### ISSUE THREAD

**Issue by dieb** [andrewrk/node-tmx-parser#6]
Hello there,

Is it possible to make tmx-parser only require zlib optionally? Maybe make it a default to automatically require it but add a switch to avoid it. It adds much code to a feature that is optional on the TMX format (compression).

If you think it's a good idea I can try to write an appropriate merge request.

Thanks!

**Comment by andrewrk** [comment]
I think nobody cares about this any more. If somebody cares they can open a new issue.
